TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB_INSTALLS += devsrsDS345.db
DB_INSTALLS += $(TOP)/srsDS345Sup/devsrsDS345.proto

#=======================================
include $(TOP)/configure/RULES
